/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Max and min values for ADC offset and gain */
#define OFFSET_MAX   127
#define OFFSET_MIN  -128
#define GAIN_MAX     15
#define GAIN_MIN    -15

/* Max ADC conversion result */
#define ADC_RESULT_MAX  4095

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Calibration setting */
cy_stc_sar2_analog_calibration_conifg_t g_calibrationConfig =
{
    .offset = OFFSET_MAX,
    .gain = 0ul,
};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: getAdcValue
 * Summary:
 *  Issues software trigger for a defined channel, waits for ADC to complete its conversion
 *  and returns converted value.
 * Parameters:
 *  channel - channel used for A/D conversion
 * Return:
 *  uint16_t - Measurement value
 **********************************************************************************************************************
 */
static uint16_t getAdcValue(uint32_t channel)
{
    /* Trigger conversion. */
    Cy_SAR2_Channel_SoftwareTrigger(SARADC_HW, channel);
    
    /* Wait for completion. */
    while (CY_SAR2_INT_GRP_DONE != Cy_SAR2_Channel_GetInterruptStatus(SARADC_HW, channel))
    {
    }
    Cy_SAR2_Channel_ClearInterrupt(SARADC_HW, channel, CY_SAR2_INT_GRP_DONE);
    
    /* Get and return the conversion result */
    return (Cy_SAR2_Channel_GetResult(SARADC_HW, channel, NULL));
}

/**********************************************************************************************************************
 * Function Name: printMenu
 * Summary:
 *  Displays a menu on a terminal window to select some actions 
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
static void printMenu(void)
{
    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("***********************************************************\r\n");
    printf("SAR ADC Calibration\r\n");
    printf("***********************************************************\r\n");
    printf(">> Select one of the options as listed below \r\n");
    printf(">> 0 : Trigger ADC Measurement\r\n");
    printf(">> 1 : Execute ADC Calibration\r\n");
    printf(">> 2 : Set ADC Offset Compensation to OFFSET_MAX\r\n");
    printf(">> 3 : Set ADC Offset Compensation to OFFSET_MIN\r\n");
    printf(">> 4 : Set ADC Gain Compensation to GAIN_MAX\r\n");
    printf(">> 5 : Set ADC Gain Compensation to GAIN_MIN\r\n\r\n");
    printf(">> Others : Print menu\r\n\r\n");
}

/**********************************************************************************************************************
 * Function Name: calibrateOffset
 * Summary:
 *  Performs ADC offset calibration.
 * Parameters:
 *  none
 * Return:
 *  bool - true if the calibration is successful.
 **********************************************************************************************************************
 */
static bool calibrateOffset(void)
{
    uint16_t result;
    int16_t offsetHigh;
    int16_t offsetLow;
    int16_t finalOffsetValue;
    
    /* Set VREF_L as source for the channel and initialize the channel. */
    SARADC_AdcChannel1_config.pinAddress = CY_SAR2_PIN_ADDRESS_VREF_L;
    Cy_SAR2_Channel_Init(SARADC_HW, SARADC_AdcChannel1_IDX, &SARADC_AdcChannel1_config);

    /* Gain configuration set to '0' while offset calibration is executed. */
    g_calibrationConfig.gain = 0;

    /* Go through all offset compensation values from max to min. */
    for (offsetLow = OFFSET_MAX; offsetLow >= OFFSET_MIN; offsetLow -= 1)
    {
        /* Set current offset value in alternate offset register. */
        g_calibrationConfig.offset = (int8_t) offsetLow;
        Cy_SAR2_SetAltAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
        
        /* Get ADC conversion value. */
        result = getAdcValue(SARADC_AdcChannel1_IDX);
        
        /* Offset calibration completed when the ADC conversion value equals to "0". */
        if (result == 0)
        {
            break;
        }
        
        /* Error condition if offset has reached lower bound. */
        if (offsetLow == OFFSET_MIN)
        {
            /* Offset adjustment failed - report error. */
            printf("Error: ADC conversion value > '0' when offset is set to OFFSET_MIN\r\n");
            return false;
        }
    }

    /* Set VREF_H as source for the channel and initialize the channel. */
    SARADC_AdcChannel1_config.pinAddress = CY_SAR2_PIN_ADDRESS_VREF_H;
    Cy_SAR2_Channel_Init(SARADC_HW, SARADC_AdcChannel1_IDX, &SARADC_AdcChannel1_config);
    
    /* Adjust the offset compensation to the smallest offset value possible. */
    g_calibrationConfig.offset = OFFSET_MIN;
    Cy_SAR2_SetAltAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
    
    /* Start ADC conversion and get the A/D value. */
    result = getAdcValue(SARADC_AdcChannel1_IDX);
    
    /* ADC conversion value must be lower than the maximal ADC result value. */
    if (result < ADC_RESULT_MAX)
    {
        /* Go through all offset compensation values from min to max. */
        for (offsetHigh = OFFSET_MIN; offsetHigh <= OFFSET_MAX; offsetHigh += 1)
        {
            /* Set current offset value in alternate offset register. */
            g_calibrationConfig.offset = (int8_t) offsetHigh;
            Cy_SAR2_SetAltAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
            
            /* Get ADC conversion value. */
            result = getAdcValue(SARADC_AdcChannel1_IDX);
            
            /* Offset calibration completed when the ADC conversion value equals to the maximum possible ADC result value. */
            if (result == ADC_RESULT_MAX)
            {
                break;
            }
            
            /* Error condition if offset has reached upper bound. */
            if (offsetHigh == OFFSET_MAX)
            {
                /* Offset adjustment failed - report error. */
                printf("Error: ADC conversion value remains below the maximum possible ADC conversion value when the offset is set OFFSET_MAX.\r\n");
                return false;
            }
        }
    }
    else
    {
        /* Offset adjustment failed - report error. */
        printf("Error: Initial ADC conversion result equals to the maximum possible ADC conversion value when the offset is set to OFFSET_MIN.\r\n");
        return false;
    }
    
    /* Calculate the final offset value and check its expected range */
    finalOffsetValue = ((offsetHigh + offsetLow) / 2) + 2;
    if (finalOffsetValue > OFFSET_MAX)
    {
        /* Offset adjustment failed - report error. */
        printf("Error: Final offset value must not greater than OFFSET_MAX\r\n");
        return false;
    }
    
    /* Update the offset compensation with the calculated value */
    g_calibrationConfig.offset = (int8_t) finalOffsetValue;
    
    /* Print the final calibrated offset value. */
    printf("ADC offset compensation value: %d\r\n", finalOffsetValue);
    return true;
}

/**********************************************************************************************************************
 * Function Name: calibrateGain
 * Summary:
 *  Performs ADC gain calibration
 * Parameters:
 *  none
 * Return:
 *  bool - true if the calibration is successful.
 **********************************************************************************************************************
 */
static bool calibrateGain(void)
{
    int8_t gain = 0;
    uint16_t result;
    
    /* Set gain correction to maximum possible gain value. */
    g_calibrationConfig.gain = GAIN_MAX;
    
    /* Set VREFL voltage to input and init the channel. */
    SARADC_AdcChannel1_config.pinAddress = CY_SAR2_PIN_ADDRESS_VREF_L;
    Cy_SAR2_Channel_Init(SARADC_HW, SARADC_AdcChannel1_IDX, &SARADC_AdcChannel1_config);
    
    /* Apply the initial calibration settings. */
    Cy_SAR2_SetAltAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
    
    /* Start ADC conversion and get the A/D value. */
    result = getAdcValue(SARADC_AdcChannel1_IDX);
    
    /* The ADC conversion result should be higher than the minimum ADC conversion value. */
    if (result > 0)
    {
         /* Decrement the value of gain compensation by "1". */
        for (gain = GAIN_MAX; gain >= GAIN_MIN; gain -= 1)
        {
            /* Set gain to calibration register */
            g_calibrationConfig.gain = gain;
            Cy_SAR2_SetAltAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);

            /* Get ADC conversion value. */
            result = getAdcValue(SARADC_AdcChannel1_IDX);

            /* Gain calibration completed when the ADC conversion value equals to the minimum ADC conversion value. */
            if (result == 0)
            {
                break;
            }
            if (gain == GAIN_MIN)
            {
                /* Gain adjustment failed - report error. */
                printf("Error: ADC conversion value > '0' when the gain is set GAIN_MIN.\r\n");
                return false;
            }
        }
    }
    else
    {
        /* Gain adjustment failed - report error. */
        printf("Error: ADC conversion result equals to '0' when the gain is set GAIN_MAX.\r\n");
        return false;
    }
    
    /* Print calibrated gain value. */
    printf("ADC gain compensation value: %d\r\n", gain);
    return true;
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function. It configures two ADC channels. One is connected to a potentiometer. 
 *  The second channel is used for ADC calibration. A menu is displayed on a terminal (115200 baud).
 *  The user can choose between different actions: 
 *   - Trigger one ADC conversion of the channel connected to the potentiometer
 *   - De-calibrate ADC by changing offset (OFFSET_MAX, OFFSET_MIN) and gain (GAIN_MAX, GAIN_MIN)
 *   - Execution of ADC calibration algorithm for offset and gain
 *  Status information are displayed for each action. Configurations for ADC and port pins are defined 
 *  in "cycfg_peripherals.h". Any changes should be done in the device configurator. 
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    uint16_t adcValue; 
    uint8_t uartReadValue;    

    #if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdt_obj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    result = cyhal_wdt_init(&wdt_obj, cyhal_wdt_get_max_timeout_ms());
    CY_ASSERT(CY_RSLT_SUCCESS == result);
    cyhal_wdt_free(&wdt_obj);
    #endif /* #if defined (CY_DEVICE_SECURE) */

    /* Initialize the device and board peripherals */
    if (cybsp_init()!= CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    if (cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Print the menu to list all options */
    printMenu();
    
    /* Set ePASS MMIO reference buffer mode for bandgap voltage */
    Cy_SAR2_SetReferenceBufferMode(PASS0_EPASS_MMIO, CY_SAR2_REF_BUF_MODE_ON);

    /* Enable the Diagnostic Reference */
    Cy_SAR2_Diag_Enable(SARADC_HW);
    
     /* Initialize the ADC */
    Cy_SAR2_Init(SARADC_HW, &SARADC_config);
    
    /* Enable ADC */
    Cy_SAR2_Enable(SARADC_HW);    
    
    for (;;)
    {
        /* Check if key was pressed and perform actions */
        if (cyhal_uart_getc(&cy_retarget_io_uart_obj, &uartReadValue, 1) == CY_RSLT_SUCCESS)
        {
            switch (uartReadValue)
            {
                /* Trigger a single ADC conversion of potentiometer voltage and display it on terminal */
                case '0':
                    printf(">> 0 : Trigger ADC Measurement\r\n");
                    adcValue = getAdcValue(SARADC_AdcChannel0_IDX);
                    printf("ADC-Value: %d\r\n", adcValue);  
                    break;
                
                /* Execute ADC calibration algorithm for offset and gain */
                case '1':
                    printf(">> 1 : Execute ADC Calibration\r\n");
                    if(calibrateOffset() == true)
                    {
                        printf("Offset Calibration successful\r\n");  
                    }
                    else
                    {
                        printf("Offset Calibration error\r\n");  
                    }

                    if(calibrateGain() == true)
                    {
                        printf("Gain Calibration successful\r\n");  
                    }
                    else
                    {
                        printf("Gain Calibration error\r\n");  
                    }
                    
                    /* Update regular calibration values based on calibration data
                     * found in alternate calibration register. */
                    Cy_SAR2_TriggerCalibrationUpdate(SARADC_HW);
                    break;
                
                /* De-calibrate ADC with offset set to OFFSET_MAX */
                case '2':
                    printf(">> 2 : Set ADC Offset Compensation to OFFSET_MAX\r\n");
                    
                    /* Set regular calibration offset to OFFSET_MAX to de-calibrate the ADC. */
                    g_calibrationConfig.offset = OFFSET_MAX;
                    Cy_SAR2_SetAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
                    printf("ADC Offset set to OFFSET_MAX\r\n");  
                    break;
                
                /* De-calibrate ADC with offset set to OFFSET_MIN */
                case '3':
                    printf(">> 3 : Set ADC Offset Compensation to OFFSET_MIN\r\n");

                    /* Set regular calibration offset to OFFSET_MIN to de-calibrate the ADC. */
                    g_calibrationConfig.offset = OFFSET_MIN;
                    Cy_SAR2_SetAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
                    printf("ADC Offset set to OFFSET_MIN\r\n");  
                    break;
                
                /* De-calibrate ADC with gain set to GAIN_MAX */
                case '4':
                    printf(">> 4 : Set ADC Gain Compensation to GAIN_MAX\r\n");
                    
                    /* Set regular calibration gain to GAIN_MAX to de-calibrate the ADC. */
                    g_calibrationConfig.gain = GAIN_MAX;
                    Cy_SAR2_SetAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
                    printf("ADC Gain set to GAIN_MAX\r\n");  
                    break;
                
                /* De-calibrate ADC with offset set to GAIN_MIN */
                case '5':
                    printf(">> 5 : Set ADC Gain Compensation to GAIN_MIN\r\n\r\n");
                    
                    /* Set regular calibration gain to GAIN_MIN to de-calibrate the ADC. */
                    g_calibrationConfig.gain = GAIN_MIN;
                    Cy_SAR2_SetAnalogCalibrationValue(SARADC_HW, &g_calibrationConfig);
                    printf("ADC Gain set to GAIN_MIN\r\n");  
                    break;
                
                /* Print menu for all other keys pressed */
                default:
                    printMenu();
                    break;                    
            }
        }        
    }
}

/* [] END OF FILE */
